webtalk_init -webtalk_dir D:/Git/LAB2_Grayscale/Lab2_JSTK2/Lab2_JSTK2.sim/sim_1/behav/xsim/xsim.dir/tb_PulseWidthModulator_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr  5 00:17:25 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fc3a9ad9-b803-40cd-99d3-a98da83b5421" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "620906f25f04426887607f668621ea38" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "76" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "23.50_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "18244_KB" -context "xsim\\usage"
webtalk_transmit -clientid 363398654 -regid "" -xml D:/Git/LAB2_Grayscale/Lab2_JSTK2/Lab2_JSTK2.sim/sim_1/behav/xsim/xsim.dir/tb_PulseWidthModulator_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Git/LAB2_Grayscale/Lab2_JSTK2/Lab2_JSTK2.sim/sim_1/behav/xsim/xsim.dir/tb_PulseWidthModulator_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Git/LAB2_Grayscale/Lab2_JSTK2/Lab2_JSTK2.sim/sim_1/behav/xsim/xsim.dir/tb_PulseWidthModulator_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
